FoodDA/Models/BaiViet.cs
namespace FoodDA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("BaiViet")]
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            Cmts = new HashSet<Cmt>();
        }

        [Key]
        public int IdBaiViet { get; set; }

        public int IdChuDe { get; set; }

        [Required(ErrorMessage = "Enter the issued date.")]
        [DataType(DataType.Date)]

        public DateTime Ngay { get; set; }


        [Required(ErrorMessage = "Tên bài viết không được để trống")]
        [Display(Name = "Tên Bài Viết")]
        public string TenBaiViet { get; set; }

        [Required(ErrorMessage = "Mô tả không được để trống")]
        [Display(Name = "Mô Ta")]
        public string MoTa { get; set; }

  
        [Required(ErrorMessage = "Tên nguyên liệu không được để trống")]
        public string NguyenLieu { get; set; }

        public string NguyenLieu1 { get; set; }

        public string NguyenLieu2 { get; set; }

        public string NguyenLieu3 { get; set; }

        public string NguyenLieu4 { get; set; }

        public string NguyenLieu5 { get; set; }

        public string NguyenLieu6 { get; set; }

        public string NguyenLieu7 { get; set; }

        public string NguyenLieu8 { get; set; }

        [Required(ErrorMessage = "Hướng dẫn không được để trống")]
        public string HuongDan { get; set; }

        public string HinhAnh1 { get; set; }

        public string HinhAnh2 { get; set; }

        public string HinhAnh3 { get; set; }

        [Required(ErrorMessage = "Link Youtube không được để trống")]
        public string LinkYoutube { get; set; }

        [Required(ErrorMessage = "Lượng kcal không được để trống")]
        public double? kcal { get; set; }

        public virtual ChuDe ChuDe { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cmt> Cmts { get; set; }
    }
}

FoodDA/Controllers/BaiVietsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodDA.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace FoodDA.Controllers
{
    public class BaiVietsController : Controller
    {
        private FoodEntities db = new FoodEntities();

        // GET: BaiViets
        public ActionResult Index(int page = 1, int pageSize = 7)
        {
            int pageNumber = page;

            return View(db.BaiViets.ToList().OrderByDescending(n => n.IdBaiViet).ToPagedList(page, pageSize));
        }

        // GET: BaiViets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            return View(baiViet);
        }

        // GET: BaiViets/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.IdChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "IdChuDe", "TenChuDe");
            return View();
        }
        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Create(BaiViet sp, HttpPostedFileBase fileupload1, HttpPostedFileBase fileupload2, HttpPostedFileBase fileupload3)
        {
            ViewBag.IdChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "IdChuDe", "TenChuDe");
            if (fileupload1 == null || fileupload2 == null || fileupload3 == null)
            {
                ViewBag.ThongBao = "Vui lòng chọn ảnh";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName1 = Path.GetFileName(fileupload1.FileName);
                    var path1 = Path.Combine(Server.MapPath("~/IMG/IMGcongthuc"), fileName1);
                    var fileName2 = Path.GetFileName(fileupload2.FileName);
                    var path2 = Path.Combine(Server.MapPath("~/IMG/IMGcongthuc"), fileName2);
                    var fileName3 = Path.GetFileName(fileupload2.FileName);
                    var path3 = Path.Combine(Server.MapPath("~/IMG/IMGcongthuc"), fileName3);
                    if (System.IO.File.Exists(path1) || System.IO.File.Exists(path2)|| System.IO.File.Exists(path3))
                        ViewBag.ThongBao = "Hình Ảnh đã tồn tại";
                    else

                    {
                        fileupload1.SaveAs(path1);
                        fileupload2.SaveAs(path2);
                        fileupload3.SaveAs(path3);
                    }
                    sp.HinhAnh1 = fileName1;
                    sp.HinhAnh2 = fileName2;
                    sp.HinhAnh3 = fileName3;
                    sp.Ngay = DateTime.Now;

                    db.BaiViets.Add(sp);
                    db.SaveChanges();
                  
                }
                return RedirectToAction("Index");

            }
            //Hiển thị chi tiết sp

        }


        // GET: BaiViets/Edit/5
        public ActionResult chitietbaiviet(int id)
        {
            BaiViet sp = db.BaiViets.SingleOrDefault(n => n.IdBaiViet == id);
            ViewBag.IdBaiViet = sp.IdBaiViet;
            if (sp == null)
            {
                Response.StatusCode = 400;
                return null;
            }
            return View(sp);
        }

        // POST: BaiViets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpGet]
        public ActionResult SuaBaiViet(int id)
        {
            BaiViet sp = db.BaiViets.SingleOrDefault(n => n.IdBaiViet == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.IdChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "IdChuDe", "TenChuDe");
            return View(sp);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaBaiViet(BaiViet sp, HttpPostedFileBase fileupload1, HttpPostedFileBase fileupload2, HttpPostedFileBase fileupload3)
        {
            ViewBag.IdChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "IdChuDe", "TenChuDe");
            if (fileupload1 == null || fileupload2 == null || fileupload3 == null)
            {
                ViewBag.ThongBao = "Vui lòng chọn ảnh";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName1 = Path.GetFileName(fileupload1.FileName);
                    var path1 = Path.Combine(Server.MapPath("~/IMG/IMGSamPham"), fileName1);
                    var fileName2 = Path.GetFileName(fileupload2.FileName);
                    var path2 = Path.Combine(Server.MapPath("~/MG/IMGSamPham"), fileName2);
                    var fileName3 = Path.GetFileName(fileupload3.FileName);
                    var path3 = Path.Combine(Server.MapPath("~/IMG/IMGSamPham"), fileName3);
                    if (System.IO.File.Exists(path1) || System.IO.File.Exists(path2) || System.IO.File.Exists(path3))
                        ViewBag.ThongBao = "Hình Ảnh đã tồn tại";
                    else
                    {
                        fileupload1.SaveAs(path1);
                        fileupload2.SaveAs(path2);
                        fileupload2.SaveAs(path3);
                    }
                    sp.HinhAnh1 = fileName1;
                    sp.HinhAnh2 = fileName2;
                    sp.HinhAnh3 = fileName3;
                    sp.Ngay = DateTime.Now;

                    db.Entry(sp).State = EntityState.Modified;
                    db.SaveChanges();

                }
                return RedirectToAction("Index");
            }
        }
        // GET: BaiViets/Delete/5
        public ActionResult xoabaiviet(int? id)
        {
            BaiViet sp = db.BaiViets.Find(id);
            db.BaiViets.Remove(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: BaiViets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BaiViet baiViet = db.BaiViets.Find(id);
            db.BaiViets.Remove(baiViet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpGet]
        public ActionResult XemChiTietBaiViet(int id)
        {
            var product = db.BaiViets.Find(id);
            ViewBag.product = product;
            ViewBag.idproduct = product.IdBaiViet;
            Session["BaiViet"] = product.IdBaiViet;
            Session["idbaiviet"] = product;
            var cmt = new Cmt()
            {
                IdBaiViet = product.IdBaiViet
            };
            ViewBag.congthuc = product.HuongDan.Contains("$");
            return View("XemChiTietBaiViet", cmt);
        }

        [HttpGet]
        public ActionResult showComment(int id = 0, int page = 1, int sizepage = 5)
        {
            ViewBag.idbaivietcm = id;
            int pageNumber = page;
            BaiViet baiviet = db.BaiViets.SingleOrDefault(n => n.IdBaiViet == id);
            var cmts = db.Cmts.Include(c => c.NguoiDung).Where(n => n.IdBaiViet == id).OrderByDescending(n=>n.Ngay).ToList();
            ViewBag.ThongBaoCMT = "Có " + cmts.Count() + " bình luận";
            return View(cmts.ToPagedList(pageNumber, sizepage));
        }

        public ActionResult SendReview(FormCollection f)
        {
            NguoiDung nguoiDung = (NguoiDung)Session["TaiKhoan"];
            BaiViet baiviet = (BaiViet)Session["idbaiviet"];
            Cmt cmt = new Cmt();
            cmt.IdNguoiDung = nguoiDung.IdNguoiDung;
            cmt.IdBaiViet = baiviet.IdBaiViet;
            cmt.Ngay = DateTime.Now;
            cmt.NoiDung = f["NoiDung"].ToString();
            cmt.rating = int.Parse(f["rating"]);
            db.Cmts.Add(cmt);
            db.SaveChanges();
            return RedirectToAction("XemChiTietBaiViet", "BaiViets", new { id = baiviet.IdBaiViet });
        }
        public ViewResult ListBaiViet(int idLoaiSamPham = 1, int page = 1, int pageSize = 5)
        {

            int pageNumber = page;
            var baiviet = db.BaiViets.ToList();
            ViewBag.CountKcal = "Đã tìm thấy " + baiviet.Count + " bài viết cho bạn";
            return View(baiviet.ToPagedList(pageNumber, pageSize));
        }
        public ViewResult ListBaiVietChuDe()
        {
            var listbaivietchude = db.ChuDes.ToList();
            return View(listbaivietchude);
        }
        [HttpPost]
        public ViewResult ListBaiVietKcal(FormCollection f, int page = 1, int sizepage = 5)
        {
            int pageNumber = page;
            float ChieuCao = float.Parse(f["txtChieuCao"]);
            float CanNang = float.Parse(f["txtCanNang"]);
            float BMI = ((CanNang / (ChieuCao * ChieuCao)) * 10000);
            ViewBag.CanNang = CanNang;
            ViewBag.ChieuCao = ChieuCao;
            ViewBag.BMI = BMI;
            if (BMI >= 40)
            {
                ViewBag.thongbaoKcal = "Béo phì cấp độ ba";
                var list = db.BaiViets.Where(n => n.kcal < 800).ToList();
                ViewBag.CountKcal = "Đã tìm thấy " + list.Count + " bài viết cho bạn";
                return View(list.ToPagedList(pageNumber, sizepage));
            }

FoodDA/Controllers/ThongKeController.cs
using FoodDA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodDA.Controllers
{
    public class ThongKeController : Controller
    {
        private FoodEntities db = new FoodEntities();
        // GET: 
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SanPham()
        {
            return View();
        }

        public ActionResult BaiViet()
        {
            return View();
        }

        public ActionResult GetPostAnalytics()
        {
            return Json(PreparePostData(), JsonRequestBehavior.AllowGet);
        }

        public List<PostStatic> PreparePostData()
        {
            List<PostStatic> listPostStatic = new List<PostStatic>();

            List<BaiViet> listPost = db.BaiViets.ToList();///

            for (int i = 1; i < 10; i++)
            {
                int Soluong = db.BaiViets.Count(x => x.ChuDe.IdChuDe == i);
                PostStatic postStatic = new PostStatic();
                postStatic.Quanity = Soluong;
                if (i == 1)
                {
                    postStatic.NameTypePost = "Món Khô";
                }
                if (i == 2)
                {
                    postStatic.NameTypePost = "Soup";
                }
                if (i == 3)
                {
                    postStatic.NameTypePost = "Món Xào";
                }
                if (i == 4)
                {
                    postStatic.NameTypePost = "Món chiên";
                }
                if (i == 5)
                {
                    postStatic.NameTypePost = "Món nướng";
                }

                listPostStatic.Add(postStatic);
            }



            return listPostStatic;
        }

        public ActionResult GetProductAnalytics()
        {
            return Json(PrepareProductData(), JsonRequestBehavior.AllowGet);
        }

        public List<PostStatic> PrepareProductData()
        {
            List<PostStatic> listPostStatic = new List<PostStatic>();

            List<SanPham> listPost = db.SanPhams.ToList();

            for (int i = 1; i < 10; i++)
            {
                int Soluong = db.SanPhams.Count(x => x.LoaiSP.IdLoaiSP == i);
                PostStatic postStatic = new PostStatic();
                postStatic.Quanity = Soluong;
                if (i == 1)
                {
                    postStatic.NameTypePost = "Dụng cụ bếp";
                }
                if (i == 2)
                {
                    postStatic.NameTypePost = "Thực phẩm ăn liền";
                }

                listPostStatic.Add(postStatic);
            }



            return listPostStatic;
        }

        public ActionResult GetBillAnalytics()
        {
            return Json(PrepareBillData(), JsonRequestBehavior.AllowGet);
        }

        public List<PostStatic> PrepareBillData()
        {
            List<PostStatic> listPostStatic = new List<PostStatic>();

            List<HoaDon> listPost = db.HoaDons
                .OrderByDescending(Party => Party.Ngay)
                .Take(30)
                .ToList();

            List<string> LoopInDay = new List<string>();

            foreach(var Bill in listPost)
            {
                var Today = Bill.Ngay;

                if (LoopInDay.Any(Day => Day.Equals(Today.ToString())) == true)
                    continue;

                LoopInDay.Add(Today.ToString());

                string TotalIncome = db.HoaDons
                    .Where(Party => Party.Ngay.Month == Today.Month)
                    .Where(Party => Party.Ngay.Year == Today.Year)
                    .Where(Party => Party.Ngay.Day == Today.Day)
                    .Sum(Party => Party.TongTien).ToString();

                PostStatic postStatic = new PostStatic();
                postStatic.Quanity = int.Parse(TotalIncome);
                postStatic.NameTypePost = "Tổng Ngày " + Today.ToString("dd/MM/yyyy");

                listPostStatic.Add(postStatic);
            }

            return listPostStatic;
        }

    }
}

FoodDA/Views/ThongKe/BaiViet.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    @Html.ActionLink("Abc", "abc")
</p>
<div>
    <h2 style="color: #2e86de; font-weight: bold; text-align: center">Thống Kê Bài Viết</h2>
</div>
<head>

    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<div>
    <div class="row" style="margin-top:10px">
        <div id="BaiViet" class="col-md-3"></div>
    </div>
    <div id="columnchart_div"></div>
</div>

<script>
    windows.onload = function () {
        $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("GetPostAnalytics", "ThongKe")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
    }

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'T');
            data.addColumn('number', 'Số lượng bài viết đang có');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.NameTypePost, obj.Quanity]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Số lượng bài viết: ",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_div'));

            columnChart.draw(data, columnChartOptions);
        }
</script>

FoodDA/Views/ThongKe/SanPham.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Session["idQuyen"].ToString() == "1")
{
    <p>
        @Html.ActionLink("Abc", "abc")
    </p>
    <div>
        <h2 style="color: red; font-weight:bold; text-align:center">Thống Kê Sản Phẩm</h2>
    </div>
    <head>

        <title>Result Visualization</title>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    </head>
    <div>
        <div class="row" style="margin-top:10px">
            <div id="SanPham" class="col-md-3"></div>
        </div>
        <div id="columnchart_div"></div>
    </div>


    <script>
    window.onload = function () {
        $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("GetProductAnalytics", "ThongKe")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
    }

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Tỉnh/Thành phố');
            data.addColumn('number', 'Số lượng sản phẩm đang bán');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.NameTypePost, obj.Quanity]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Số lượng sản phẩm: ",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
}
else if (Session["idQuyen"].ToString() != "1")
{
    <h1>
        BẠN KHÔNG THỂ VÀO PHẦN NÀY
    </h1>
}

FoodDA/Views/ThongKe/index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Session["idQuyen"].ToString() == "1")
{
    <p>
        @Html.ActionLink("Abc", "abc")
    </p>
    <div>
        <h2 style="color: #2e86de; font-weight: bold; text-align: center">
            Thống Kê Sản Phẩm
            <span>(30 Ngày Gần Nhất)</span>
        </h2>
    </div>
    <head>

        <title>Result Visualization</title>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    </head>
    <div>
        <div class="row" style="margin-top:10px">
            <div id="BaiViet" class="col-md-3"></div>
        </div>
        <div id="columnchart_div"></div>
    </div>

    <script>
window.onload = function () {
             $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("GetBillAnalytics", "ThongKe")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        }

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'T');
            data.addColumn('number', 'Tổng Thu');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.NameTypePost, obj.Quanity]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Số lượng bài viết: ",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
}
else if (Session["idQuyen"].ToString() != "1")
{
    <h1>
        BẠN KHÔNG THỂ VÀO PHẦN NÀY
    </h1>
}