FoodDA/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoodDA.Models;
using PagedList;
using PagedList.Mvc;

namespace FoodDA.Controllers
{
    public class TimKiemController : Controller
    {
        FoodEntities db = new FoodEntities();
        // GET: TimKiem
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int page = 1, int sizepage = 5)
        {
            int pageNumber = page;
            String tukhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = tukhoa;
            var listkq = db.BaiViets.Where(n => n.TenBaiViet.Contains(tukhoa)).ToList();
            ViewBag.ThongBao = "Tìm thấy " + listkq.Count + " bài viết";
            return View(listkq.OrderBy(n => n.TenBaiViet).ToPagedList(pageNumber, sizepage));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(String tukhoa, int page = 1, int sizepage = 5)
        {
            int pageNumber = page;
            ViewBag.TuKhoa = tukhoa;
            var listkq = db.BaiViets.Where(n => n.TenBaiViet.Contains(tukhoa)).ToList();
            ViewBag.ThongBao = "Tìm thấy " + listkq.Count + " bài viết";
            return View(listkq.OrderBy(n => n.TenBaiViet).ToPagedList(pageNumber, sizepage));
        }
        [HttpPost]
        public ActionResult KetQuaTimKiemsampham(FormCollection f, int page = 1, int sizepage = 5)
        {
            int pageNumber = page;
            String tukhoa = f["txtTimKiemsanpham"].ToString();
            ViewBag.TuKhoa = tukhoa;
            var listkq = db.SanPhams.Where(n => n.TenSP.Contains(tukhoa)).ToList().ToPagedList(pageNumber, sizepage);
            ViewBag.ThongBao = "Tìm thấy " + listkq.Count + " Sản phẩm";
            return View(listkq);
        }
        [HttpGet]
        public ActionResult KetQuaTimKiemsampham(String tukhoa, int page = 1, int sizepage = 5)
        {
            int pageNumber = page;
            ViewBag.TuKhoa = tukhoa;
            var listkq = db.SanPhams.Where(n => n.TenSP.Contains(tukhoa)).ToList().ToPagedList(pageNumber, sizepage);
            ViewBag.ThongBao = "Tìm thấy " + listkq.Count + " Sản phẩm";
            return View(listkq);
        }

    }

}

FoodDA/Views/TimKiem/KetQuaTimKiem.cshtml
@using FoodDA.Models
@using PagedList.Mvc
@model PagedList.IPagedList<BaiViet>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListBaiViet</title>
    <link href="~/Content/Trang chu/TrangChu.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/SanPhamChiTiet.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/ListBaiViet.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/ListLoaiSanPham.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/PageList.css" rel="stylesheet" />
    <script src="~/Content/JavaScript/jquery-3.2.1.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet" />
    <script>
        jQuery(document).ready(function () {
            jQuery('.home__myself').click(function () {
                jQuery('.Trangcanhan').toggleClass('Trangcanhan__show')
            })
            jQuery('#Header__menu__info').click(function () {
                jQuery('.nav.navbar-nav.navbar-right').toggleClass('nav.navbar-navnavbar-right__show')
            })
            jQuery('#Header__menu__info').click(function () {
                jQuery('.Sucess').toggleClass('Sucess__show')
            })
            jQuery('#dangky').click(function () {
                jQuery('.DangNhappartial').removeClass('DangNhappartial__show')
                jQuery('.DangKypartial').toggleClass('DangKypartial__show')
                jQuery('.ForgotPasswordpartial').removeClass('ForgotPasswordpartial__show')
            })
            jQuery('#dangnhap').click(function () {
                jQuery('.DangKypartial').removeClass('DangKypartial__show')
                jQuery('.DangNhappartial').toggleClass('DangNhappartial__show')
                jQuery('.ForgotPasswordpartial').removeClass('ForgotPasswordpartial__show')
            })
            jQuery('#quenmatkhau').click(function () {
                jQuery('.DangNhappartial').removeClass('DangNhappartial__show')
                jQuery('.DangKypartial').removeClass('DangKypartial__show')
                jQuery('.ForgotPasswordpartial').toggleClass('ForgotPasswordpartial__show')
            })
            jQuery(window).scroll(function () {
                if (jQuery(this).scrollTop()) {
                    jQuery('.Header__menu').addClass('sticky5');
                    jQuery('.Header__menu__list').addClass('sticky');
                    jQuery('.Header__logo').addClass('sticky1');
                    jQuery('li.haha').addClass('sticky2');
                    jQuery('.fa-align-justify').addClass('sticky3');
                    jQuery('.introduce').addClass('.introduce__sticky');
                    jQuery('.Trangcanhan').addClass('.Trangcanhan__sticky');
                    jQuery('.radius__border').addClass('.radius__border__sticky');
                    jQuery('.a__home--hover').addClass('.a__home--hover--sticky');
                }
                else {
                    jQuery('.Header__menu').removeClass('sticky5');
                    jQuery('.Header__menu__list').removeClass('sticky');
                    jQuery('.Header__logo').removeClass('sticky1');
                    jQuery('li.haha').removeClass('sticky2');
                    jQuery('.fa-align-justify').removeClass('sticky3');
                    jQuery('.introduce').removeClass('.introduce__sticky');
                    jQuery('.Trangcanhan').removeClass('.Trangcanhan__sticky');
                    jQuery('.radius__border').removeClass('.radius__border__sticky');
                    jQuery('.a__home--hover').removeClass('.a__home--hover--sticky');
                }
            })
        })
    </script>
</head>
<body>
    <header id="Header">
        <div class="Header__menu">
            <div class="Header__logo"></div>
            <ul class="Header__menu__list">
                <li class="haha"><a href="@Url.Action("SanPhamList", "SanPham")">Sản phẩm</a></li>
                <li class="haha"><a href="@Url.Action("ListBaiViet", "BaiViets")">Công thức nấu ăn</a></li>
                <li class="haha"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                <li class="haha"><a href="@Url.Action("DungCuLamBepList", "SanPham")">Dụng cụ nhà bếp</a></li>
                <li class="haha"><a href="@Url.Action("GioHang", "GioHang")">Giỏ hàng (@Html.Action("GioHangPartial", "GioHang"))</a></li>
            </ul>
        </div>
        <div class="Partialview__Loai__SP__CT">
            <div class="List__Loai__SP__partial">@Html.Action("ListLoaiSanPham", "SanPham")</div>
            <div class="List__Loai__SP__partial">@Html.Action("ListBaiVietChuDe", "BaiViets")</div>
        </div>
        <h2>@ViewBag.thongbao</h2>
        @foreach (var item in Model)
        {
            <div class="List__BaiViet">
                <div class="Header">
                    <div class="tin__all__BaiViet">
                        <div class="Border__List__baiViet"></div>
                        <div class="background__shadow__List__baiViet"></div>
                        <div class="Header__NoiDung__BaiViet__TenBaiViet"><a class="a__list__baiviet" href="@Url.Action("XemChiTietBaiViet","BaiViets",new {id=item.IdBaiViet})">@item.TenBaiViet</a></div>
                        <div class="Header__img__BaiViet">
                            <img alt="@item.HinhAnh1" src="~/IMG/IMGcongthuc/@item.HinhAnh1" class="Header__img__BaiViet__HA1" />
                            <img alt="@item.HinhAnh2" src="~/IMG/IMGcongthuc/@item.HinhAnh2" class="Header__img__BaiViet__HA2" />
                            <img alt="@item.HinhAnh3" src="~/IMG/IMGcongthuc/@item.HinhAnh3" class="Header__img__BaiViet__HA3" />
                        </div>
                    </div>
                    <div class="Header__NoiDung__BaiViet">
                        <div class="Header__NoiDung__BaiViet__Mota">
                            MÔ TẢ: @item.MoTa.ToString().Substring(0, 100) ...
                        </div>
                        <div class="Header__NoiDung__BaiViet__NguyenLieu">
                            NGUYÊN LIỆU: @item.NguyenLieu.ToString().Substring(0, 100) ...
                        </div>
                    </div>
                </div>
            </div>
        }
    </header>
    <div class="MenuTrang" style="display:inline">
        Trang @(Model.PageCount<Model.PageNumber ? 0:Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiem", "TimKiem", new { @page = page, @tukhoa = ViewBag.TuKhoa }))
    </div>
</body>
</html>
<style>
    a.Search {
        color: #8a2be29e;
    }

    h2 {
        position: absolute;
        top: 72px;
        font-family: monospace;
        left: 169px;
    }
</style>

FoodDA/Views/TimKiem/KetQuaTimKiemsampham.cshtml
@using FoodDA.Models
@using PagedList.Mvc
@model PagedList.IPagedList<SanPham>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListBaiViet</title>
    <link href="~/Content/Trang chu/TrangChu.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/ListBaiViet.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/ListSanPham.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/ListLoaiSanPham.css" rel="stylesheet" />
    <link href="~/Content/Trang chu/PageList.css" rel="stylesheet" />
    <script src="~/Content/JavaScript/jquery-3.2.1.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet" />
    <script>
        jQuery(document).ready(function () {
            jQuery('.home__myself').click(function () {
                jQuery('.Trangcanhan').toggleClass('Trangcanhan__show')
            })
            jQuery('#Header__menu__info').click(function () {
                jQuery('.nav.navbar-nav.navbar-right').toggleClass('nav.navbar-navnavbar-right__show')
            })
            jQuery('#Header__menu__info').click(function () {
                jQuery('.Sucess').toggleClass('Sucess__show')
            })
            jQuery('#dangky').click(function () {
                jQuery('.DangNhappartial').removeClass('DangNhappartial__show')
                jQuery('.DangKypartial').toggleClass('DangKypartial__show')
                jQuery('.ForgotPasswordpartial').removeClass('ForgotPasswordpartial__show')
            })
            jQuery('#dangnhap').click(function () {
                jQuery('.DangKypartial').removeClass('DangKypartial__show')
                jQuery('.DangNhappartial').toggleClass('DangNhappartial__show')
                jQuery('.ForgotPasswordpartial').removeClass('ForgotPasswordpartial__show')
            })
            jQuery('#quenmatkhau').click(function () {
                jQuery('.DangNhappartial').removeClass('DangNhappartial__show')
                jQuery('.DangKypartial').removeClass('DangKypartial__show')
                jQuery('.ForgotPasswordpartial').toggleClass('ForgotPasswordpartial__show')
            })
            jQuery(window).scroll(function () {
                if (jQuery(this).scrollTop()) {
                    jQuery('.Header__menu').addClass('sticky5');
                    jQuery('.Header__menu__list').addClass('sticky');
                    jQuery('.Header__logo').addClass('sticky1');
                    jQuery('li.haha').addClass('sticky2');
                    jQuery('.fa-align-justify').addClass('sticky3');
                    jQuery('.introduce').addClass('.introduce__sticky');
                    jQuery('.Trangcanhan').addClass('.Trangcanhan__sticky');
                    jQuery('.radius__border').addClass('.radius__border__sticky');
                    jQuery('.a__home--hover').addClass('.a__home--hover--sticky');
                }
                else {
                    jQuery('.Header__menu').removeClass('sticky5');
                    jQuery('.Header__menu__list').removeClass('sticky');
                    jQuery('.Header__logo').removeClass('sticky1');
                    jQuery('li.haha').removeClass('sticky2');
                    jQuery('.fa-align-justify').removeClass('sticky3');
                    jQuery('.introduce').removeClass('.introduce__sticky');
                    jQuery('.Trangcanhan').removeClass('.Trangcanhan__sticky');
                    jQuery('.radius__border').removeClass('.radius__border__sticky');
                    jQuery('.a__home--hover').removeClass('.a__home--hover--sticky');
                }
            })
        })
    </script>
</head>
<body>
    <header id="Header">
        <div class="Header__menu">
            <div class="Header__logo"></div>
            <ul class="Header__menu__list">
                <li class="haha"><a href="@Url.Action("SanPhamList", "SanPham")">Sản phẩm</a></li>
                <li class="haha"><a href="@Url.Action("ListBaiViet", "BaiViets")">Công thức nấu ăn</a></li>
                <li class="haha"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                <li class="haha"><a href="@Url.Action("DungCuLamBepList", "SanPham")">Dụng cụ nhà bếp</a></li>
                <li class="haha"><a href="@Url.Action("GioHang", "GioHang")">Giỏ hàng (@Html.Action("GioHangPartial", "GioHang"))</a></li>
            </ul>
        </div>
        <div class="Partialview__Loai__SP__CT">
            <div class="List__Loai__SP__partial">@Html.Action("ListLoaiSanPham", "SanPham")</div>
            <div class="List__Loai__SP__partial">@Html.Action("ListBaiVietChuDe", "BaiViets")</div>
        </div>
        <div class="Result">
            @ViewBag.ThongBao
        </div>
        @foreach (var item in Model)
        {
            <div class="List__BaiViet">
                <div class="Header">
                    <div class="tin__all__BaiViet">
                        <div class="Border__List__baiViet"></div>
                        <div class="background__shadow__List__baiViet"></div>
                        <div class="Header__NoiDung__BaiViet__TenBaiViet"><a class="a__list__baiviet" href="@Url.Action("XemChiTietSanPham","SanPham",new {@IdSanPham=item.IdSanPham })">@item.TenSP</a></div>
                        <div class="Header__img__BaiViet">
                            <img alt="@item.HinhAnh1" src="~/IMG/IMGSamPham/@item.HinhAnh1" class="Header__img__BaiViet__HA1" />
                            <img alt="@item.HinhAnh2" src="~/IMG/IMGSamPham/@item.HinhAnh2" class="Header__img__BaiViet__HA2" />
                        </div>
                    </div>
                    <div class="Header__NoiDung__BaiViet">
                        <div class="Header__NoiDung__BaiViet__Mota">
                            MÔ TẢ:@item.MoTa.ToString().Substring(0, 100)...
                            <div class="Prince__Produce__List">Giá tiền: @item.Gia</div>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="MenuTrang" style="display:inline">
            Trang @(Model.PageCount<Model.PageNumber ? 0:Model.PageNumber)/@Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiemsanpham", "TimKiem", new { page = page, @tukhoa = ViewBag.TuKhoa }))
        </div>
    </header>
</body>
</html>
<style>
    .Result {
        /* justify-content: center; */
        margin-left: 12%;
        font-size: 20px;
        font-family: monospace;
        margin-top:3%;
    }

    a.Search {
        color: #8a2be29e;
    }
    .List__BaiViet {
        margin-bottom: -81px;
        margin-top: 64px;
    }
</style>